color0 #3f4948
color1 #ffb4ab
color2 #80d5d3
color3 #b0cccb
color4 #b2c8e8
color5 #80d5d3
color6 #b0cccb
color7 #dde4e3
color8 #889392
color9 #ffb4ab
color10 #80d5d3
color11 #b0cccb
color12 #b2c8e8
color13 #80d5d3
color14 #b0cccb
color15 #dde4e3

cursor                #dde4e3
cursor_text_color     #0e1514
background            #0e1514
foreground            #dde4e3
selection_foreground  #bec9c8
selection_background  #3f4948
active_border_color   #80d5d3
inactive_border_color #3f4948
url_color             #80d5d3

active_tab_foreground   #003736
active_tab_background   #80d5d3
inactive_tab_foreground #bec9c8
inactive_tab_background #3f4948
cursor_trail_color      #bec9c8
