general {
    lock_cmd = noctalia msg session lock || loginctl lock-session
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

# 1. Dim screen brightness after 2.5 minutes (150s) of inactivity
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# 2. Turn off keyboard backlight after 2.5 minutes (150s) of inactivity
listener {
    timeout = 150
    on-timeout = brightnessctl -s -d "apple::kbd_backlight" set 0%
    on-resume = brightnessctl -r -d "apple::kbd_backlight"
}

# 3. Turn off display backlight (DPMS) after 5 minutes (300s) of inactivity
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 4. Suspend machine (with auto-hibernate delay) after 15 minutes (900s) of inactivity
listener {
    timeout = 900
    on-timeout = systemctl suspend-then-hibernate
}
