[colors.primary]
background = '#151218'
foreground = '#e7e0e8'

[colors.cursor]
text = '#151218'
cursor = '#e7e0e8'

[colors.vi_mode_cursor]
text = '#151218'
cursor = '#d4bbfc'

[colors.search.matches]
foreground = '#49454e'
background = '#f1b7c4'

[colors.search.focused_match]
foreground = '#49454e'
background = '#d4bbfc'

[colors.footer_bar]
foreground = '#49454e'
background = '#e7e0e8'

[colors.hints.start]
foreground = '#49454e'
background = '#cdc2db'

[colors.hints.end]
foreground = '#49454e'
background = '#cdc2db'

[colors.selection]
text = '#cbc4cf'
background = '#49454e'


[colors.normal]
black   = '#49454e'
red     = '#ffb4ab'
green   = '#d4bbfc'
yellow  = '#cdc2db'
blue    = '#f1b7c4'
magenta = '#d4bbfc'
cyan    = '#cdc2db'
white   = '#e7e0e8'


[colors.bright]
black   = '#948f99'
red     = '#ffb4ab'
green   = '#d4bbfc'
yellow  = '#cdc2db'
blue    = '#f1b7c4'
magenta = '#d4bbfc'
cyan    = '#cdc2db'
white   = '#e7e0e8'


[colors.dim]
black   = '#49454e'
red     = '#ffb4ab'
green   = '#d4bbfc'
yellow  = '#cdc2db'
blue    = '#f1b7c4'
magenta = '#d4bbfc'
cyan    = '#cdc2db'
white   = '#e7e0e8'
