color0 #49454e
color1 #ffb4ab
color2 #d4bbfc
color3 #cdc2db
color4 #f1b7c4
color5 #d4bbfc
color6 #cdc2db
color7 #e7e0e8
color8 #948f99
color9 #ffb4ab
color10 #d4bbfc
color11 #cdc2db
color12 #f1b7c4
color13 #d4bbfc
color14 #cdc2db
color15 #e7e0e8

cursor                #e7e0e8
cursor_text_color     #151218
background            #151218
foreground            #e7e0e8
selection_foreground  #cbc4cf
selection_background  #49454e
active_border_color   #d4bbfc
inactive_border_color #49454e
url_color             #d4bbfc

active_tab_foreground   #39255c
active_tab_background   #d4bbfc
inactive_tab_foreground #cbc4cf
inactive_tab_background #49454e
cursor_trail_color      #cbc4cf
