color0 #42474e
color1 #ffb4ab
color2 #9ccbfb
color3 #b9c8da
color4 #d4bee6
color5 #9ccbfb
color6 #b9c8da
color7 #e0e2e8
color8 #8c9199
color9 #ffb4ab
color10 #9ccbfb
color11 #b9c8da
color12 #d4bee6
color13 #9ccbfb
color14 #b9c8da
color15 #e0e2e8

cursor                #e0e2e8
cursor_text_color     #101418
background            #101418
foreground            #e0e2e8
selection_foreground  #c2c7cf
selection_background  #42474e
active_border_color   #9ccbfb
inactive_border_color #42474e
url_color             #9ccbfb

active_tab_foreground   #003354
active_tab_background   #9ccbfb
inactive_tab_foreground #c2c7cf
inactive_tab_background #42474e
cursor_trail_color      #c2c7cf
