[colors.primary]
background = '#0f1416'
foreground = '#dee3e6'

[colors.cursor]
text = '#0f1416'
cursor = '#dee3e6'

[colors.vi_mode_cursor]
text = '#0f1416'
cursor = '#89d0ed'

[colors.search.matches]
foreground = '#40484c'
background = '#c4c3eb'

[colors.search.focused_match]
foreground = '#40484c'
background = '#89d0ed'

[colors.footer_bar]
foreground = '#40484c'
background = '#dee3e6'

[colors.hints.start]
foreground = '#40484c'
background = '#b3cad5'

[colors.hints.end]
foreground = '#40484c'
background = '#b3cad5'

[colors.selection]
text = '#c0c8cc'
background = '#40484c'


[colors.normal]
black   = '#40484c'
red     = '#ffb4ab'
green   = '#89d0ed'
yellow  = '#b3cad5'
blue    = '#c4c3eb'
magenta = '#89d0ed'
cyan    = '#b3cad5'
white   = '#dee3e6'


[colors.bright]
black   = '#8a9296'
red     = '#ffb4ab'
green   = '#89d0ed'
yellow  = '#b3cad5'
blue    = '#c4c3eb'
magenta = '#89d0ed'
cyan    = '#b3cad5'
white   = '#dee3e6'


[colors.dim]
black   = '#40484c'
red     = '#ffb4ab'
green   = '#89d0ed'
yellow  = '#b3cad5'
blue    = '#c4c3eb'
magenta = '#89d0ed'
cyan    = '#b3cad5'
white   = '#dee3e6'
