[colors.primary]
background = '#0f1512'
foreground = '#dee4de'

[colors.cursor]
text = '#0f1512'
cursor = '#dee4de'

[colors.vi_mode_cursor]
text = '#0f1512'
cursor = '#8cd5b4'

[colors.search.matches]
foreground = '#404944'
background = '#a6ccdf'

[colors.search.focused_match]
foreground = '#404944'
background = '#8cd5b4'

[colors.footer_bar]
foreground = '#404944'
background = '#dee4de'

[colors.hints.start]
foreground = '#404944'
background = '#b3ccbe'

[colors.hints.end]
foreground = '#404944'
background = '#b3ccbe'

[colors.selection]
text = '#bfc9c2'
background = '#404944'


[colors.normal]
black   = '#404944'
red     = '#ffb4ab'
green   = '#8cd5b4'
yellow  = '#b3ccbe'
blue    = '#a6ccdf'
magenta = '#8cd5b4'
cyan    = '#b3ccbe'
white   = '#dee4de'


[colors.bright]
black   = '#89938d'
red     = '#ffb4ab'
green   = '#8cd5b4'
yellow  = '#b3ccbe'
blue    = '#a6ccdf'
magenta = '#8cd5b4'
cyan    = '#b3ccbe'
white   = '#dee4de'


[colors.dim]
black   = '#404944'
red     = '#ffb4ab'
green   = '#8cd5b4'
yellow  = '#b3ccbe'
blue    = '#a6ccdf'
magenta = '#8cd5b4'
cyan    = '#b3ccbe'
white   = '#dee4de'
