[colors.primary]
background = '#0e1514'
foreground = '#dde4e3'

[colors.cursor]
text = '#0e1514'
cursor = '#dde4e3'

[colors.vi_mode_cursor]
text = '#0e1514'
cursor = '#80d5d3'

[colors.search.matches]
foreground = '#3f4948'
background = '#b2c8e8'

[colors.search.focused_match]
foreground = '#3f4948'
background = '#80d5d3'

[colors.footer_bar]
foreground = '#3f4948'
background = '#dde4e3'

[colors.hints.start]
foreground = '#3f4948'
background = '#b0cccb'

[colors.hints.end]
foreground = '#3f4948'
background = '#b0cccb'

[colors.selection]
text = '#bec9c8'
background = '#3f4948'


[colors.normal]
black   = '#3f4948'
red     = '#ffb4ab'
green   = '#80d5d3'
yellow  = '#b0cccb'
blue    = '#b2c8e8'
magenta = '#80d5d3'
cyan    = '#b0cccb'
white   = '#dde4e3'


[colors.bright]
black   = '#889392'
red     = '#ffb4ab'
green   = '#80d5d3'
yellow  = '#b0cccb'
blue    = '#b2c8e8'
magenta = '#80d5d3'
cyan    = '#b0cccb'
white   = '#dde4e3'


[colors.dim]
black   = '#3f4948'
red     = '#ffb4ab'
green   = '#80d5d3'
yellow  = '#b0cccb'
blue    = '#b2c8e8'
magenta = '#80d5d3'
cyan    = '#b0cccb'
white   = '#dde4e3'
